---
title: "R Notebook"
output: html_notebook
---

```{r}
unispace <- rbind(
  modelling %>% mutate(is.train = TRUE),
  submitting %>% mutate(is.train = FALSE, class = NA)
)
```

```{r}
df <- unispace
check.na(df)
```
```{r}
df.plot <- df %>% pivot_longer(cols = c("cap.diameter", "stem.height", "stem.width"), names_to = "Numeric", values_to = "Value")
ggplot(df.plot) +
  geom_density(aes(log1p(Value), color = class, fill = class), alpha = 0.4) +
  facet_wrap(~ Numeric, scales = "free", ncol = 1)
ggplot(df.plot) +
  geom_boxplot(aes(Numeric, Value))
```

```{r}
filter(df, cap.diameter > 600)

df <- df %>%
  mutate(cap.diameter = ifelse(cap.diameter > 200, NA, cap.diameter)) 

check.na(df %>% select(where(is.numeric)))
new.df <- df %>%
      clean.numeric() %>%
      clean.categories() %>%
      fill.with.cap.diameter() %>%
      fill.with.stem.width() %>%
      fill.with.stem.height() %>%
      clean.ring() %>%
      clean.bruise() 

new.df <- new.df %>% mutate_at(vars(gill.attachment, gill.spacing),
                 function(x) replace_na(x, Mode(x, na.rm = TRUE)))

new.df$class
new.df <- new.df %>%
  select(-contains("cut_interval")) 
str(new.df)
new.df <- new.df %>%
  mutate(class = ifelse(is.na(class), NA, ifelse(class == "p", 1, 0))) %>%
  mutate_if(is.character, factor)

new.df <- new.df %>%
  mutate_if(is.factor, as.integer)
check.na(new.df)


```

```{r}
X <- new.df %>% select(-id, -is.train, -class)
y <- new.df$class
str(X)
y
```

```{r}
library(mice)
block = list(b = c("stem.root", "stem.surface", "veil.type", "veil.color", "spore.print.color"))

imp <- mice(X, m = 1)
imp_X <- complete(imp)                        
```

```{r}
Xtrain <- imp_X[df$is.train,]
ytrain <- y[df$is.train]
Xtest <- imp_X[!df$is.train,]
```

```{r}
test_ind <- createDataPartition(ytrain, p = 0.3, list = FALSE)
train.input <- as.matrix(Xtrain[-test_ind, ])
train.y <- ytrain[-test_ind]
test.input <- as.matrix(Xtrain[test_ind, ])
test.y <- ytrain[test_ind]
```

```{r}
xg_2 <- train(train.input, as.factor(train.y),
              method = "xgbTree",
              trControl = trainControl(method = "none",
                                       verboseIter = FALSE,
                                       allowParallel = TRUE)
              )
library(xgboost)
train.input
xg_2 <- xgboost(train.input, train.y, 
                 params = list(
                   max_depth = 8,
                   eta = 0.4, 
                   gamma = 0.04,
                   colsample_bytree = 1,
                   min_child_weight = 1,
                   subsample = 0.7
                 ), 
                 nrounds = 100,
                 objective = "binary:hinge")
train.y
pred_2 <- predict(xg_2, test.input)
pred_2
confusionMatrix(as.factor(predict(xg_2, test.input)), as.factor(test.y))
```
```{r}
test.output <- predict(xg_2, as.matrix(Xtest))
submission_2 <- data.frame(
  id = submitting$id,
  class = ifelse(test.output == 1, "p", "e")
)
write.csv(submission_2, "submission_2.csv", row.names = FALSE)
```

